# SPDX-FileCopyrightText: 2024 Katoh Takuma
# SPDX-License-Identifier: BSD-3-Clause

name: Homework1 Test
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Execute homework1 tests
        run: |
          chmod +x ./test1.bash
          ./test1.bash

